name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: appleboy/ssh-action@master
      with:
        host: 34.27.119.80
        username: dev.danielboggiano
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Conexión exitosa"
          cd /home/dev.danielboggiano/docker-gcp-deployment && sudo sh deploy.sh
